### PR TITLE
Packages from Testprojects will marked as scope="excluded"

### PR DESCRIPTION
**Pull request by patspaeth**
related to issue #415 

Additionally implemented that the order of scope is required before excluded.

### CODE REVIEW

**Comment by coderpatros** [comment]
Something is really weird with this PR. Did you start from an up to date cut of the master branch?

**Comment by coderpatros** [comment]
Having looked at this some more, are you doing something like manually bringing in commits to an internal fork?

**Comment by patspaeth** [comment]
> Having looked at this some more, are you doing something like manually bringing in commits to an internal fork?

I really do not know, I was just executing this DCO step https://github.com/CycloneDX/cyclonedx-dotnet/pull/416/checks?check_run_id=3359182914 and then the whole history is now in this PR.

I created my fork when I have done my last changes, then made a sync with the origin (merge commits) and made on top of this my changes

**Comment by patspaeth** [comment]
I will refork and re-do the changes. Hopefully it is working then

**Pull request closed without merging**
