### PR TITLE
Removal of support for  .NET 2.1 and .NET5, reference upgrades, changed from httpclient to Nuget SDK

### LINKED ISSUE #430: Breaking change - drop support for .NET Core 2.1 runtime
.NET Core 2.1 is now out of support. The next major version will remove support for that runtime.

Note: this _shouldn't_ affect the ability to generate a BOM for .NET Core 2.1 projects. It just means this tool will no longer _run_ if you only have the 2.1 runtime installed.

### LINKED ISSUE #512: KeyNotFoundException throws when create Bom
I got error KeyNotFoundException, I am using cyclone-dotnet 2.3.0

Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'airc.loggingsdk.common' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CycloneDX.Program.OnExecuteAsync()
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 113
   at CycloneDX.Program.<Main>(String[] args)

### LINKED ISSUE #518: KeyNotFoundException with version interval
Test version: github master branch

I am getting a KeyNotFoundException. The error happens at the following line, `dep` is `'(awssdk.core, [3.7.8.9, 4.0.0))` but `bomRefLookup` contains `("awssdk.core", "3.7.8.9")`. This might be related to #512. I will try to make reproduction project I can share.

```csharp
transitiveDepencies.Add(bomRefLookup[(dep.Key.ToLower(CultureInfo.InvariantCulture), dep.Value.ToLower(CultureInfo.InvariantCulture))]);
```
https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/CycloneDX/Program.cs#L286

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '(awssdk.core, [3.7.8.9, 4.0.0))' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CycloneDX.Program.OnExecuteAsync() in C:\dev\External\cyclonedx\cyclonedx-dotnet\CycloneDX\Program.cs:line 286
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in C:\dev\External\cyclonedx\cyclonedx-dotnet\CycloneDX\Program.cs:line 116
   at CycloneDX.Program.<Main>(String[] args)
```

### LINKED ISSUE #533: SHA512Managed is obsolete
Warning during compilation:

warning SYSLIB0021: 'SHA512Managed' is obsolete: 'Derived cryptographic types are obsolete. Use the Create method on the base type instead.'

### PR DESCRIPTION
**Pull request by verzada**
- [x] remove support for .NET 5 and .NET 2.1
- [x] Resolved #516 with the help of the other PR
- [x] fix issues from code report (code refactoring)
- [x] change from httpClient to Nuget 6.0 api for nuspec handlig
- [x] add apikey support for authenticated Nuget feeds (testing required)
- [x] Resolved #517 
- [x] Resolved #518 
- [x] Resolved #512
- [x] upgrade package components
- [x] Fix missing license text
- [x] Fix command options text added for Nuget credentials
- [x] Resolved #533 since the issue is fixed in this PR
- [x] Fix typo: Depencies -> Dependencies
- [x] Resolved #529 
- [x] Resolved #528 
- [x] Resolved #491 
- [x] Resolved #484 
- [x] Resolved #430 
- [x] Update Readme.Md with the removal of .NET 2.1 (and .NET5) compatibility information

### CODE REVIEW

**Comment by verzada** [comment]
@coderpatros  So much work to fix the signoff. Hope the code is okay now.

**Comment by verzada** [comment]
Added more isuses that are solved in this PR

**Comment by RodneyRichardson** [comment]
Are you planning to update the README as well (such as removing reference to .net 2.1, etc)?

**Comment by verzada** [comment]
> Are you planning to update the README as well (such as removing reference to .net 2.1, etc)?

Yeah, that should be fixed too

**Comment by verzada** [comment]
Updated Readme.md file with currently supported .NET versions and which versions are deprecated (and why).

**Comment by verzada** [comment]
Saw there are a bunch of updates that arrived last night, better to add those in a new PR. Lots of changes in this PR already.

**Review by coderpatros — APPROVED** [review]

**Pull request merged**
